repos:
  - repo: https://github.com/pycqa/flake8
    rev: 3.9.2
    hooks:
      - id: flake8

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        language: system
        types: [file, python]

  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports

  - repo: https://github.com/fsfe/reuse-tool
    rev: v0.13.0
    hooks:
      - id: reuse

  - repo: https://github.com/hadolint/hadolint
    rev: 3b1de5a  # todo: pin to to >=v2.7.1 whenever that's released
    hooks:
      - id: hadolint-docker
