# SPDX-FileCopyrightText: Magenta ApS
#
# SPDX-License-Identifier: MPL-2.0
version: 2
updates:
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: daily
    auto-merge: true
    rebase-strategy: all
