# Generated by ariadne-codegen on 2025-11-10 15:33
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class CreateClassMutation(BaseModel):
    class_create: "CreateClassMutationClassCreate"


class CreateClassMutationClassCreate(BaseModel):
    uuid: UUID


CreateClassMutation.update_forward_refs()
CreateClassMutationClassCreate.update_forward_refs()
