# Generated by ariadne-codegen on 2026-05-08 14:12
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class CreateITSystemMutation(BaseModel):
    itsystem_create: "CreateITSystemMutationItsystemCreate"


class CreateITSystemMutationItsystemCreate(BaseModel):
    uuid: UUID


CreateITSystemMutation.update_forward_refs()
CreateITSystemMutationItsystemCreate.update_forward_refs()
