# Generated by ariadne-codegen on 2026-05-08 14:12
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class RootOrgCreate(BaseModel):
    org_create: "RootOrgCreateOrgCreate"


class RootOrgCreateOrgCreate(BaseModel):
    uuid: UUID


RootOrgCreate.update_forward_refs()
RootOrgCreateOrgCreate.update_forward_refs()
