# Generated by ariadne-codegen on 2026-05-08 14:12
# Source: queries.graphql

from uuid import UUID

from .base_model import BaseModel


class UpdateITSystemMutation(BaseModel):
    itsystem_update: "UpdateITSystemMutationItsystemUpdate"


class UpdateITSystemMutationItsystemUpdate(BaseModel):
    uuid: UUID


UpdateITSystemMutation.update_forward_refs()
UpdateITSystemMutationItsystemUpdate.update_forward_refs()
